/**
 * 공통 레이아웃
 */
import "./globals.css";
import AppNavigation from "./components/AppNavigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="root">
        <AppNavigation />
        {children}
      </body>
    </html>
  );
}
